# Generated by Django 4.2 on 2025-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0003_category_document_introduction_projects_delete_about_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='flloca/pics'),
        ),
    ]
