# Generated by Django 4.2 on 2025-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0004_projects_slug_alter_projects_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=False),
        ),
    ]
