# Generated by Django 4.2 on 2025-07-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0005_projects_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
