# Generated by Django 4.2 on 2025-07-16 14:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0007_ourprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.TextField()),
                ('intro', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
