# Generated by Django 4.2 on 2025-07-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0008_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurProjects',
        ),
    ]
