# Generated by Django 4.2 on 2025-07-16 14:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flloca', '0009_delete_ourprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='flloca/pics')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='Draft', max_length=10)),
                ('created_date', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
