# Generated by Django 4.2 on 2025-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0010_ourprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojects',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
