# Generated by Django 4.2 on 2025-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0012_alter_ourprojects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojects',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
