# Generated by Django 4.2 on 2025-07-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0014_alter_ourprojects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='created_date',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='OurProjects',
        ),
    ]
