# Generated by Django 4.2 on 2025-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FllocaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='intro',
            new_name='flloca_intro',
        ),
    ]
