# Generated by Django 4.2 on 2025-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0017_fllocagallery_rename_intro_introduction_flloca_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroFlloca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('twitter', models.CharField(max_length=40)),
                ('facebook', models.CharField(max_length=40)),
                ('youtube', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='pics')),
                ('hero_bg', models.ImageField(upload_to='pics')),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
            ],
        ),
    ]
