# Generated by Django 4.2 on 2025-07-16 21:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flloca', '0019_deptheads'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grievances', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='deptheads',
            name='img',
            field=models.ImageField(upload_to='flloca/pics'),
        ),
        migrations.AlterField(
            model_name='fllocagallery',
            name='img',
            field=models.ImageField(upload_to='flloca/pics'),
        ),
        migrations.AlterField(
            model_name='heroflloca',
            name='hero_bg',
            field=models.ImageField(upload_to='flloca/pics'),
        ),
        migrations.AlterField(
            model_name='heroflloca',
            name='logo',
            field=models.ImageField(upload_to='flloca/pics'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='img',
            field=models.ImageField(upload_to='flloca/pics'),
        ),
    ]
