# Generated by Django 4.2 on 2025-07-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0007_executives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executives',
            old_name='designation',
            new_name='title',
        ),
    ]
