# Generated by Django 4.2 on 2025-07-08 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0008_rename_designation_executives_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deptheads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('bio', models.TextField()),
                ('email', models.CharField(max_length=25)),
                ('twitter', models.CharField(max_length=40)),
                ('facebook', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='Draft', max_length=10)),
            ],
        ),
    ]
