# Generated by Django 4.2 on 2025-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0009_deptheads'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('logo', models.ImageField(upload_to='pics')),
                ('hero_bg', models.ImageField(upload_to='pics')),
                ('text_1', models.TextField()),
            ],
        ),
    ]
