# Generated by Django 4.2 on 2025-07-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0010_heroothers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroothers',
            name='logo',
        ),
    ]
