# Generated by Django 4.2 on 2025-07-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0012_contactsubmission_alter_departments_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
