# Generated by Django 4.2 on 2025-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0013_delete_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=100)),
                ('rights_text', models.CharField(max_length=100)),
                ('developed_by', models.CharField(max_length=100)),
                ('developer_link', models.CharField(max_length=100)),
            ],
        ),
    ]
