# Generated by Django 4.2 on 2025-07-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0015_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='promovideos/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active promotional video is displayed at a time.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Promotional Videos',
            },
        ),
    ]
