# Generated by Django 4.2 on 2025-07-13 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0016_promotionalvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
