# Generated by Django 4.2 on 2025-07-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0017_partners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
