# Generated by Django 4.2 on 2025-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0020_moha_alter_departments_email_alter_deptheads_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moha',
        ),
    ]
