# Generated by Django 4.2 on 2025-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0021_delete_moha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executives',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
