# Generated by Django 4.2 on 2025-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0022_alter_executives_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
