# Generated by Django 4.2 on 2025-07-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0026_alter_departments_slug_alter_deptheads_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copyright',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Deptheads',
        ),
        migrations.DeleteModel(
            name='Executives',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='HeroOthers',
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
        migrations.RemoveField(
            model_name='news',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='PromotionalVideo',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
