# Generated by Django 4.2 on 2025-07-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsabitweb', '0028_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
